### PR TITLE
port to GNOME 45

### PR DESCRIPTION
**Pull request by HonzaCholasta**

### CODE REVIEW

**Comment by bulletmark** [comment]
@HonzaCholasta it seems this extension is now unmaintained. Your GNOME 45+ version is very different code to what is here so perhaps you may consider renaming it a different extension and putting it on extensions.gnome.org/?

**Comment by timbertson** [comment]
Thanks for this, I can't easily test since I don't have a working gnome45 setup, so I've been procrastinating 😅 

But it looks reasonable, assuming you've tested it I'm happy to release because it'll probably take me a while to get around to testing this myself 👍

**Comment by bulletmark** [comment]
@timbertson I installed it on Arch which is running GNOME 45 and it works fine, including the config display/function.

**Comment by mschubert** [comment]
I can confirm his works well on Arch. @timbertson can we get a tag/release as well for stable packaging?

**Comment by pschichtel** [comment]
@timbertson thanks for also releasing it to the extensions page, but can you also set a tag here so package maintainers can updated? thanks!

**Comment by timbertson** [comment]
👍 version-0.5.0

The gnome.org update is in review, so it might not be available for a little while yet 😞

**Pull request merged**
