### PR TITLE
Add Gnome Shell 43 compatibility

### PR DESCRIPTION
**Pull request by jssotomdz**
This requires no code changes

### CODE REVIEW

**Comment by feimosi** [comment]
@jssotomdz @timbertson I'm not familiar with the release process of gnome extensions but 43 is missing from the compatibility list here: https://extensions.gnome.org/extension/277/impatience/

**Comment by real-or-random** [comment]
@feimosi I assume this is because a release hasn't been created yet.

**Comment by feimosi** [comment]
I see, @timbertson any chance to create a new release? Thanks.

**Comment by timbertson** [comment]
Done, sorry for the delay.

**Pull request merged**
